Class {
	#name : #SPOCApiTrackHistory,
	#superclass : #SPOCApiEndpoint,
	#category : #SpotifyConnect
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'VK 5/28/2024 17:26'
}
SPOCApiTrackHistory >> endpoint [
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'VK 5/28/2024 17:26'
}
SPOCApiTrackHistory >> endpointMethod [	
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'VK 5/28/2024 17:28'
}
SPOCApiTrackHistory >> executeRequest: request withParams: aParameterDictionary [
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'VK 5/28/2024 17:26'
}
SPOCApiTrackHistory >> executeTest [
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'VK 5/28/2024 17:27'
}
SPOCApiTrackHistory >> tinkerReponseContent: aContentStream [
]
